import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TrendMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* Header */}
        <header className="bg-white shadow-md p-4 sticky top-0 z-10">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold text-gray-900">TrendMart</h1>
            <nav className="flex space-x-4">
              <a href="/" className="hover:underline text-gray-800">Home</a>
              <a href="/categories" className="hover:underline text-gray-800">Categories</a>
              <a href="/deals" className="hover:underline text-gray-800">Deals</a>
              <a href="/about" className="hover:underline text-gray-800">About</a>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className="flex-grow">{children}</main>

        {/* Footer */}
        <footer className="bg-gray-800 text-white py-4 sticky bottom-0 z-10">
          <div className="container mx-auto text-center">
            <p>© 2023 ShopEasy. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
